//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

public class default_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.TextBox txtFiltro;
protected global::System.Web.UI.WebControls.Repeater aspRepeater;
protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCards;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
public void @__DataBind__control4(object sender, System.EventArgs e) {
System.Web.UI.WebControls.RepeaterItem Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));

#line 1 "C:\Users\KernDev\AppData\Local\Temp\CE354FC84677D5BB4C2A186F18DC7686D9E1\3\TP3-ASPNET-Equipo17\Default.aspx"
@__o = Eval("Id") ;

#line default
#line hidden
}
public void @__DataBind__control5(object sender, System.EventArgs e) {
System.Web.UI.WebControls.RepeaterItem Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));

#line 2 "C:\Users\KernDev\AppData\Local\Temp\CE354FC84677D5BB4C2A186F18DC7686D9E1\3\TP3-ASPNET-Equipo17\Default.aspx"
@__o = Eval("Nombre");

#line default
#line hidden

#line 3 "C:\Users\KernDev\AppData\Local\Temp\CE354FC84677D5BB4C2A186F18DC7686D9E1\3\TP3-ASPNET-Equipo17\Default.aspx"
@__o = Eval("Descripcion") ;

#line default
#line hidden

#line 4 "C:\Users\KernDev\AppData\Local\Temp\CE354FC84677D5BB4C2A186F18DC7686D9E1\3\TP3-ASPNET-Equipo17\Default.aspx"
@__o = Eval("Precio") ;

#line default
#line hidden
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
private void @__Render__control3(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {

#line 5 "C:\Users\KernDev\AppData\Local\Temp\CE354FC84677D5BB4C2A186F18DC7686D9E1\3\TP3-ASPNET-Equipo17\Default.aspx"
                      foreach(dominio.Articulo item in ListaArticulos){ 

#line default
#line hidden
object @__o;

#line 6 "C:\Users\KernDev\AppData\Local\Temp\CE354FC84677D5BB4C2A186F18DC7686D9E1\3\TP3-ASPNET-Equipo17\Default.aspx"
@__o =  ListaPrimerasImagenes.Find(x => x.IdArticulo == int.Parse(#Eval("Id"))).ImagenUrl ;

#line default
#line hidden

#line 7 "C:\Users\KernDev\AppData\Local\Temp\CE354FC84677D5BB4C2A186F18DC7686D9E1\3\TP3-ASPNET-Equipo17\Default.aspx"
                      
                        
                        }

#line default
#line hidden
}
}
}
